fix conflict

diff --git a/.github/workflows/test_merge_group.yml b/.github/workflows/test_merge_group.yml
--- a/.github/workflows/test_merge_group.yml
+++ b/.github/workflows/test_merge_group.yml
@@ -41,4 +41,5 @@ jobs:
   
 
       - name: Fail!
-        run: echo "::error :: :poo:" && exit 1
+        run: |
+          echo "::error :: :poo:" && exit 1
