fail

diff --git a/.github/workflows/test_merge_group.yml b/.github/workflows/test_merge_group.yml
--- a/.github/workflows/test_merge_group.yml
+++ b/.github/workflows/test_merge_group.yml
@@ -38,3 +38,6 @@ jobs:
       - name: job 2 / step 2
         run: echo "job 2 / step 2"
   
+
+      - name: Fail!
+        run: echo "::error :poo:" && exit 1
