haha

diff --git a/.github/workflows/test_merge_group.yml b/.github/workflows/test_merge_group.yml
--- a/.github/workflows/test_merge_group.yml
+++ b/.github/workflows/test_merge_group.yml
@@ -29,7 +29,7 @@ jobs:
 
       - name: Fail!
         run: |
-          echo "::error :: :poo:" && exit 1
+          echo "::error :: :poo: haha" && exit 1
 
   job2-push:
     runs-on: ubuntu-latest
